name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Debug Go environment
      run: |
        echo "=== Current directory ==="
        pwd
        echo "=== Directory contents ==="
        ls -la
        echo "=== Contents of cmd directory ==="
        ls -la cmd/
        echo "=== Go environment ==="
        go version
        go env

    - name: Install dependencies
      run: |
        go mod download
        go mod tidy

    - name: Run tests
      run: |
        go test -v ./cmd/hello_world/...
        if [ $? -ne 0 ]; then
          echo "Tests failed"
          exit 1
        fi

    - name: Run linter
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Debug Go environment
      run: |
        echo "=== Current directory ==="
        pwd
        echo "=== Directory contents ==="
        ls -la
        echo "=== Contents of cmd directory ==="
        ls -la cmd/
        echo "=== Go environment ==="
        go version
        go env

    - name: Build
      run: |
        go build -v ./cmd/hello_world
        if [ $? -ne 0 ]; then
          echo "Build failed"
          exit 1
        fi

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: hello_world
        path: hello_world 